"""Ajout du timestamp sur Ticket

Revision ID: aa6a7e6783ec
Revises: 7fb4f7f51788
Create Date: 2025-04-18 17:13:48.779039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6a7e6783ec'
down_revision = '7fb4f7f51788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
